blog/apps/fswy/urls.py
# from .views import (IndexView, DetailView, MessageView, AboutView, DonateView, ExchangeView, ProjectView, QuestionView,MySearchView)
#                     # MySearchView, LoveView, LinkView)
#
#
# urlpatterns = [
#     # 首页
#     path('', IndexView.as_view(template_name='index.html'), name='index'), # 主页，自然排序
#     # path('category/<str:bigslug>/<slug>', IndexView.as_view(template_name='content.html'), name='category'),
#     # 分类页面
#     re_path(r'^category/(?P<bigslug>.*?)/(?P<slug>.*?)',
#             IndexView.as_view(template_name='content.html'),
#             name='category'),
#     # path(r'category/about/', AboutView, name='about'),
#
#     # 给我留言
#     path(r'category/message/', MessageView, name='message'),
#     # 关于自己
#     path(r'category/about/', AboutView, name='about'),
#     # 赞助作者
#     path(r'category/donate/', DonateView, name='donate'),
#     # 技术交流
#     path(r'category/exchange/', ExchangeView, name='exchange'),
#     # 项目合作
#     path(r'category/project/', ProjectView, name='project'),
#     # 提问交流
#     path(r'category/question/', QuestionView, name='question'),
#     # 分类页面
#     # re_path(r'^category/(?P<bigslug>.*?)/(?P<slug>.*?)', IndexView.as_view(template_name='content.html'), name='category'),
#     # 归档页面
#     re_path(r'^date/(?P<year>\d+)/(?P<month>\d+)/$', IndexView.as_view(template_name='archive.html'), name='date'),
#     # 标签页面
#     re_path(r'^tag/(?P<tag>.*?)/$', IndexView.as_view(template_name='content.html'), name='tag'),
#     # 文章详情页面
#     re_path(r'^article/(?P<slug>.*?)/$', DetailView.as_view(), name='article'),
#     # 全文搜索
#     re_path(r'^search/$', MySearchView.as_view(), name='search'),
#
#     # re_path(r'^category/about/$', AboutView, name='about'),
# ]
from django.conf.urls import url
from django.urls import path,re_path
from .views import (IndexView, DetailView, MessageView, AboutView, DonateView, ExchangeView, ProjectView, QuestionView, MySearchView, LoveView, LinkView)

urlpatterns = [
    # 首页
    # url(r'^$', IndexView.as_view(template_name='index.html'), name='index'),  # 主页，自然排序
    path(r'', IndexView.as_view(template_name='index.html'), name='index'), # 主页，自然排序

    # 申请友情链接
    # url(r'^link/$', LinkView, name='link'),
    path(r'link/', LinkView, name='link'),

    # 给我留言
    # url(r'^category/message/$', MessageView, name='message'),
    path(r'category/message/', MessageView, name='message'),

    # 关于自己
    # url(r'^category/about/$', AboutView, name='about'),
    path(r'category/about/', AboutView, name='about'),

    # 赞助作者
    path(r'category/donate/', DonateView, name='donate'),
    # url(r'^category/donate/$', DonateView, name='donate'),

    # 技术交流
    path(r'category/exchange/', ExchangeView, name='exchange'),
    # url(r'^category/exchange/$', ExchangeView, name='exchange'),

    # 项目合作
    path(r'category/project/', ProjectView, name='project'),
    # url(r'^category/project/$', ProjectView, name='project'),

    # 提问交流
    path(r'category/question/', QuestionView, name='question'),
    # url(r'^category/question/$', QuestionView, name='question'),

    # 分类页面
    # url(r'^category/(?P<bigslug>.*?)/(?P<slug>.*?)', IndexView.as_view(template_name='content.html'), name='category'),
    re_path(r'^category/(?P<bigslug>.*?)/(?P<slug>.*?)', IndexView.as_view(template_name='content.html'), name='category'),

    # 归档页面
    # url(r'^date/(?P<year>\d+)/(?P<month>\d+)/$', IndexView.as_view(template_name='archive.html'), name='date'),
    re_path(r'^date/(?P<year>\d+)/(?P<month>\d+)/$', IndexView.as_view(template_name='archive.html'), name='date'),


    # 标签页面
    # url(r'^tag/(?P<tag>.*?)/$', IndexView.as_view(template_name='content.html'), name='tag'),
    re_path(r'^tag/(?P<tag>.*?)/$', IndexView.as_view(template_name='content.html'), name='tag'),

    # 文章详情页面
    # url(r'^article/(?P<slug>.*?)/$', DetailView.as_view(), name='article'),
    re_path(r'^article/(?P<slug>.*?)/$', DetailView.as_view(), name='article'),

    # 全文搜索
    # url(r'^search/$', MySearchView.as_view(), name='search'),
    path(r'search/', MySearchView.as_view(), name='search'),

    # 喜欢
    # url(r'^love/$', LoveView, name='love'),
    path(r'love/', LoveView, name='love'),


]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.sitemaps.views import sitemap
from apps.fswy.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap

from django.conf import settings
from rest_framework.routers import DefaultRouter
from apps.api import views as api_views
from apps.fswy.feeds import AllArticleRssFeed
if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users', api_views.UserListSet)
    router.register(r'articles', api_views.ArticleListSet)
    router.register(r'tags', api_views.TagListSet)
    router.register(r'categorys', api_views.CategoryListSet)

app_name = 'fswy'

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}


urlpatterns = [
    # 后台管理应用，django自带
    path('admin/', admin.site.urls),
    # 用户
    path('accounts/', include(('apps.user.urls', "apps.user"), namespace="accounts")),
    # fswy 应用
    path('', include(('apps.fswy.urls', "apps.fswy"), namespace="blog")),
    # 评论栏
    path('comment/', include(('apps.comment.urls','apps.comment'), namespace='comment')),
    # 网站地图
    # re_path(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path(r'sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # rss订阅
    path(r'feed/', AllArticleRssFeed(), name='rss'),

    path(r'mdeditor/', include(('mdeditor.urls', 'mdeditor'), namespace='mdeditor')),

]
if settings.API_FLAG:
    urlpatterns.append(path(r'api/v1/', include((router.urls, 'router'), namespace='api')))    # restframework

blog/templates/archive.html
{%extends 'base_right.html'%}
{% load comment_tags %}
{% block title %}甫式人生丨文章归档{% endblock title %}
{% block description %}
    <meta name="description" content="文章按照月份分类归档。"/>
    {% endblock description %}
{% block keywords %}
    <meta name="keywords" content="网络爬虫工具,爬虫python,http代理,scrapy爬虫,爬虫代理ip,python为什么叫爬虫,python爬虫怎么赚钱"/>
    {% endblock keywords %}
{%block body%}
	<div class="content-wrap">
	    <div class="content">
		    <header class="archive-header">
			    <h1><i class="fa fa-folder-open"></i>  &nbsp;分类：福利专区  <a title="订阅福利专区" target="_blank" href="{% url 'blog:category' resources '' %}"><i class="rss fa fa-rss"></i></a></h1>
					</header>
        {% for article in page_obj %}
				<article class="excerpt">
	<header><a class="label label-important" href="/category/{{ article.category.bigcategory.name }}/{{ article.category.name|lower }}">{{ article.category.name }}<i class="label-arrow"></i></a><h2><a target="_blank" href="/article/{{ article.slug }}" title="{{ article.title }}">{{ article.title }} </a></h2>
	</header>
	<div class="focus"><a target="_blank" href="/article/{{ article.slug }}"><img class="thumb" width="200" height="123" src="{{ article.img_link }}" alt="{{ article.title }}" /></a></div>
			<span class="note"> {{ article.summary }}</span>
<p class="auth-span">
		<span class="muted"><i class="fa fa-user"></i> <a href="/author/{{ article.author }}">{{ article.author }}</a></span>
		<span class="muted"><i class="fa fa-clock-o"></i> {{ article.create_date|date:'Y-m-d'}}</span>	<span class="muted"><i class="fa fa-eye"></i> {{ article.views }}浏览</span>	<span class="muted"><i class="fa fa-comments-o"></i> <a target="_blank" href="/article/{{ article.slug }}#comments">{% get_comment_count article.id  article.id%}评论</a></span><span class="muted">
<a href="javascript:;" data-action="ding" data-id="455" id="Addlike" class="action"><i class="fa fa-heart-o"></i><span class="count">{{ article.love }}</span>喜欢</a></span></p>
</article>
        {% empty %}
                <div class="no-post">当前分类下还没有发布的文章！</div>
        {% endfor %}
{% if is_paginated %}
            <div class="pagination">
                <ul>
                    {% if first %}
                        <li><a href="?page=1">1</a></li>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                        {% for i in left %}
                            <li class="prev-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                    {% endif %}
                    <li class="active"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>
                    {% if right %}
                        {% for i in right %}
                            <li class="next-page"><a href="?page={{ i }}">{{ i }}</a></li>
                        {% endfor %}
                        {% if right_has_more %}
                            <li><span>...</span></li>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
{%endblock body%}

blog/templates/base_right.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% block right %}
<aside class="sidebar">
    <div class="widget widget_text">
        <div class="textwidget">
            <div class="social">

                <a href="https://weibo.com/cuiqingcai" rel="external nofollow" title="新浪微博" target="_blank"><i class="sinaweibo fa fa-weibo"></i></a>
                <a  href="http://t.qq.com/CQCcqc123456?preview" rel="external nofollow" title="腾讯微博" target="_blank"><i class="tencentweibo fa fa-tencent-weibo"></i></a>
                <a class="weixin"><i class="weixins fa fa-weixin"></i>
                    <div class="weixin-popover">
                        <div class="popover bottom in">
                            <div class="arrow"></div>
                            <div class="popover-title"></div>
                            <div class="popover-content"><img src="../static/images/weixin.gif" ></div>
                        </div>
                    </div>
                </a>
                <a href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=cqc@cuiqingcai.com" rel="external nofollow" title="Email" target="_blank"><i class="email fa fa-envelope-o"></i></a>
                <a href="/feed/" rel="external nofollow" target="_blank" title="订阅本站"><i class="rss fa fa-rss"></i></a>
            </div>
        </div>
    </div>

    <div class="widget widget_metaslider_widget">
        <!-- 热门专题-->
        <div class="title"><h2>热门专题</h2></div><!-- meta slider -->
        <div style="width: 100%;" class="metaslider metaslider-nivo metaslider-2698 ml-slider meta-slider">
            <div id="metaslider_container_2698">
                <div class='slider-wrapper theme-bar'>
                    <div class='ribbon'></div>
                    <div id='metaslider_2698' class='nivoSlider'>
                        {% get_carousel_right as carousels %}
                        {% for carousel in carousels %}
                        <a href="{{ carousel.url }}" target="_blank">
                            <img src="{{ carousel.img_url }}" height="300" width="320" data-title="{{ carousel.content }}" title="{{ carousel.title }}" alt="{{ carousel.title }}" class="slider-2698 slide-1720" />
                        </a>
                        {% endfor %}

                    </div>
                </div>
            </div>
            <!--热门专题结束 -->

            <script type="text/javascript">
                var metaslider_2698 = function($) {
                    $('#metaslider_2698').nivoSlider({
                        boxCols:7,
                        boxRows:5,
                        pauseTime:3000,
                        effect:"random",
                        controlNav:false,
                        directionNav:true,
                        pauseOnHover:true,
                        animSpeed:600,
                        prevText:"&lt;",
                        nextText:"&gt;",
                        slices:15,
                        manualAdvance:false
                    });
                };
                var timer_metaslider_2698 = function() {
                    var slider = !window.jQuery ? window.setTimeout(timer_metaslider_2698, 100) : !jQuery.isReady ? window.setTimeout(timer_metaslider_2698, 1) : metaslider_2698(window.jQuery);
                };
                timer_metaslider_2698();
            </script>
        </div>
    </div>
<!--// meta slider-->
    <div class="widget widget_text">
        <div class="textwidget"><p><a href="https://1024dada.com/?channel=cuiqingcai&#038;hmsr=%E5%B4%94%E5%BA%86%E6%89%8D&#038;hmpl=&#038;hmcu=&#038;hmkw=&#038;hmci="><img style="width: 100%;" src="/static/images/timͼƭ20181112165556.jpg" /><br />
</a></p></div>
    </div>
    <div class="widget widget_text">
        <div class="textwidget">
            <a href="https://developer.huaweicloud.com/campus?utm_source=cuiqingcai&utm_medium=blog&utm_campaign=campus"><img style="width:100%" src="/static/images/云服务器学生优惠套餐9元月.jpg"/></a>
        </div>
    </div>
    <!--文章归档 -->
    <div class="widget widget_archive">
        <div class="title"><h2>文章归档</h2></div>
        {% get_data_date as data_date %}
        <ul>
            {% if data_date %}
                {% for date in data_date %}
            <li><a href='{% url 'blog:date' date|date:'Y' date|date:'m' %}'>{{ date|date:'Y-m' }}</a></li>
                {% endfor %}
            {% else %}
                <div>近期没有发表过文章</div>
            {% endif %}
        </ul>
    </div>
    <!--文章归档结束 -->
    <!--猜你喜欢 -->
    <div class="widget d_postlist">
        <div class="title"><h2>猜你喜欢</h2></div>
        <ul>
            {%  get_article_list 'loves' 6 as hot_tag %}
            {% for hot in hot_tag %}
            <li>
                <a href="/article/{{ hot.slug }}" title="{{ hot.title }}" >
                <span class="thumbnail">
                <img src="{{ hot.img_link }}" alt="{{ hot.title }}" />
                </span>
                <span class="text">{{ hot.title }}</span>
                <span class="muted">{{ hot.create_date|date:'Y-m-d' }}</span>
                <span class="muted">{{ hot.loves }}喜欢</span>
                </a>
            </li>

            {% endfor %}
        </ul>
    </div>
    <!--猜你喜欢结束 -->
    <!--标签云 -->
    <div class="widget d_tag">
        <div class="title"><h2>标签云</h2></div>
        <div class="d_tags">
            {% get_tag_list as tags %}
            {% for tag in tags %}

            <!--tag.total_num直接获得标签次标签下的文章数 -->
            <a title="{{ tag.total_num }}个话题" href="{% url 'blog:tag' tag.name %}">{{ tag.name }}({{ tag.total_num }})</a>
            {% endfor %}

        </div>
    </div>
    <!--标签云结束-->

    <!--友情链接 -->
    <div class="widget widget_links">
        <div class="title"><h2>友情链接</h2></div>
            {% get_friends as friends %}
            <ul class='xoxo blogroll'>
                {% if friends %}
                    {% for friend in friends %}
                <li><a href="http://www.99banzou.com" target="_blank">99伴奏网</a></li>
                    {% endfor %}
                {% else %}
                    <div>&nbsp;&nbsp;暂无友链，欢迎来战</div>
                {% endif %}
            </ul>
    </div>
    <!--友情链接结束 -->
    <div class="widget widget_text">
        <div class="title"><h2>精品推荐</h2></div>
        <div class="textwidget">
            <div class="side-ad">
                <script type="text/javascript">
                            var cpro_id="u2578794";
            (window["cproStyleApi"] = window["cproStyleApi"] || {})[cpro_id]={at:"3",rsi0:"300",rsi1:"250",pat:"17",tn:"baiduCustNativeAD",rss1:"#FFFFFF",conBW:"1",adp:"1",ptt:"0",titFF:"%E5%BE%AE%E8%BD%AF%E9%9B%85%E9%BB%91",titFS:"14",rss2:"#00a67c",titSU:"0"}
                </script>
                <script src="../static/js/c.js" type="text/javascript"></script>
            </div>
            <style>
                #BAIDU_SSP__wrapper_u2578794_1 {
                display:none;
                }
                #BAIDU_SSP__wrapper_u2578794_0 #iframeu2578794_0  .bd-logo2 {
                display:none !important;
                }
            </style>
        </div>
    </div>
    <div class="widget widget_text">
        <div class="title"><h2>新浪微博</h2></div>
        <div class="textwidget">
            <iframe width="100%" class="share_self"  frameborder="0" scrolling="no" src="https://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=1&uid=2830678474&verifier=7468dc7b&dpc=1">

            </iframe>
        </div>
    </div>
    <div class="widget widget_text">
        <div class="textwidget">
            <a href="https://edu.hellobi.com/course/157" style="display:none"><img src="../static/images/wx20180104-140302.png"/></a>
        </div>
    </div>
</aside>
{% endblock %}

blog/templates/comment_list.html
{% load static %}
{% load comment_tags oauth_tags %}
<div id="respond" class="no_webshot">
		<form action="/comment/add" method="post" id="commentform">

		<div class="comt-title">
            {% if request.session.username|default:'' != '' %}
            {% get_user_data request.session.uid as user %}
                <div class="comt-avatar pull-left">
                    <img alt='' src='/media/{{ user.avatar }}' class='avatar avatar-54 photo avatar-default' height='54' width='54' />			    </div>
                <div class="comt-author pull-left" id="nick">
                {{ request.session.username }}
                </div>
            {% endif %}

            {% if request.session.nick|default:'' != '' %}
                {% get_tourist_data request.session.tid as tourist %}
                <div class="comt-avatar pull-left">
                    <img alt='' src='/media/avatar' class='avatar avatar-54 photo avatar-default' height='54' width='54' />			    </div>
                <div class="comt-author pull-left" id="nick">
                {{ tourist.nickname }}

                &nbsp; <a class="switch-author" href="javascript:;" data-type="switch-author" style="font-size:12px;">换个身份</a>

                </div>
                {% else %}

                <div class="comt-author pull-left" id="nick">

                </div>
            {% endif %}

			<a id="cancel-comment-reply-link" class="pull-right" href="javascript:;">取消评论</a>
		</div>

		<div class="comt">
			<div class="comt-box">
                <h3>发表我的评论</h3>
				<textarea placeholder="写点什么..." class="input-block-level comt-area" name="w" id="comment" cols="100%" rows="3" tabindex="1" onkeydown="if(event.ctrlKey&amp;&amp;event.keyCode==13){document.getElementById('submit').click();return false};"></textarea><textarea name="comment" cols="100%" rows="4" style="display:none"></textarea>
				<div class="comt-ctrl">
					<button class="btn btn-primary pull-right" type="submit" name="submit" id="submit" tabindex="5"><i class="fa fa-check-square-o"></i> 提交评论</button>
					<div class="comt-tips pull-right"><input type='hidden' name='comment_post_ID' value='{{ category }}' id='comment_post_ID' />
<input type='hidden' name='comment_parent' id='comment_parent' value='0' />
<p style="display: none;"><input type="hidden" id="akismet_comment_nonce" name="akismet_comment_nonce" value="da9dc5c77a" /></p><p style="display: none;"><input type="hidden" id="ak_js" name="ak_js" value="50"/></p></div>
					<span data-type="comment-insert-smilie" class="muted comt-smilie"><i class="fa fa-smile-o"></i> 表情</span>
					<span class="muted comt-mailme"><label for="comment_mail_notify" class="checkbox inline" style="padding-top:0"><input type="checkbox" name="comment_mail_notify" id="comment_mail_notify" value="comment_mail_notify" checked="checked"/>有人回复时邮件通知我</label></span>
				</div>
			</div>

												<div class="comt-comterinfo" id="comment-author-info" >
						<h4>Hi，您需要填写昵称和邮箱！</h4>
						<ul>
							<li class="form-inline"><label class="hide" for="author">昵称</label><input class="ipt" type="text" name="author" id="author" value="{% if user %}{{ user.username }}{% elif tourist %}{{ tourist.nickname }}{% endif %}" tabindex="2" placeholder="昵称"><span class="help-inline">昵称 (必填)</span></li>
							<li class="form-inline"><label class="hide" for="email">邮箱</label><input class="ipt" type="text" name="email" id="email" value="{% if user %}{{ user.email }}{% elif tourist %}{{ tourist.email }}{% endif %}" tabindex="3" placeholder="邮箱"><span class="help-inline">邮箱 (必填)</span></li>
							<li class="form-inline"><label class="hide" for="url">网址</label><input class="ipt" type="text" name="url" id="url" value="{% if user %}{{ user.link }}{% elif tourist %}{{ tourist.address }}{% endif %}" tabindex="4" placeholder="网址"><span class="help-inline">网址</span></li>
						</ul>
					</div>
									</div>


	</form>
	</div>

<div id="postcomments">

{% if category == 'message'%}

    {% get_comment_user_count category as  user_num%}
    {% build_comment_tree category request.path as htm %}
{% elif category == 'about' %}
    {% get_comment_user_count category as  user_num%}
    {% build_comment_tree category request.path as htm %}
{% else %}
    {% get_comment_user_count category category as  user_num%}
    {% build_comment_tree category  request.path category as htm %}
{% endif %}
<div id="comments">
		<i class="fa fa-comments-o"></i> <b> ({{ user_num }})</b>个小伙伴在吐槽
	</div>
   {{ htm }}
<div class="commentnav"	>
			</div>
</div>

blog/templates/link.html
{%extends 'base.html' %}
{% load blog_tags %}
{%block title%}甫式人生丨添加友链{%endblock title%}

{%block body%}
<div class="pagewrapper clearfix">
    <header class="pageheader clearfix">
        <h1 class="pull-left">
            <a href="https://cuiqingcai.com/link">申请友链</a>
        </h1>
        <div class="pull-right">
            <!-- 百度分享 -->
            <span class="action action-share bdsharebuttonbox">
                <i class="fa fa-share-alt"></i>
                分享 (<span class="bds_count" data-cmd="count" title="累计分享0次">0</span>)
                <div class="action-popover">
                    <div class="popover top in">
                        <div class="arrow">
                        </div>
                        <div class="popover-content">
                            <a href="#" class="sinaweibo fa fa-weibo" data-cmd="tsina" title="分享到新浪微博"></a>
                            <a href="#" class="bds_qzone fa fa-star" data-cmd="qzone" title="分享到QQ空间"></a>
                            <a href="#" class="tencentweibo fa fa-tencent-weibo" data-cmd="tqq" title="分享到腾讯微博"></a>
                            <a href="#" class="qq fa fa-qq" data-cmd="sqq" title="分享到QQ好友"></a>
                            <a href="#" class="bds_renren fa fa-renren" data-cmd="renren" title="分享到人人网"></a>
                            <a href="#" class="bds_weixin fa fa-weixin" data-cmd="weixin" title="分享到微信"></a>
                            <a href="#" class="bds_more fa fa-ellipsis-h" data-cmd="more"></a>
                        </div>
                    </div>
                </div>
            </span>
        </div>
    </header>
        <div class="article-content">
            <!-- link -->
            <div class="friend-link">
                <h2 style="text-align: center;">友链互添</h2>
                <h3 style="text-align: center;">友链互添标准</h3>
                <blockquote style="text-align: center; line-height: 25px;">
                    <p>贵站必须有二十篇以上技术类别原创文章</p>
                    <p>贵站如两个月没有更新本站则会取消友链</p>
                    <p>贵站如一个月无法访问本站则会取消友链</p>
                    <p>贵站如取消本站友链本站则取消贵站友链</p>
                    <p>贵站如有访问或地址更新请及时通知本站</p>
                </blockquote>
                <h3 class="icon-contact" style="text-align: center;">友链互添方式</h3>
                <div class="icon-contact" style="text-align: center;">本站名称：fswy</div>
                <div class="icon-contact" style="text-align: center;">本站地址：<a href="http://fswy.com">http://fswy.com</a></div>
                <h4 class="icon-contact" style="text-align: center;">同步添加方式</h4>
                <div class="icon-contact" style="text-align: center;">1. 私信官方新浪微博 @<a href="https://weibo.com/u/5392727577" target="_blank">fswy博客</a>，附上贵站名称及地址，如符合要求，我会与你取得联系并互相添加友链。</div>
                <div class="icon-contact" style="text-align: center;">2. 邮件至 fswy@foxmail.com，附上贵站名称及地址，如符合要求，我会与你取得联系并互相添加友链。</div>
                <h4 class="icon-contact" style="text-align: center;">异步添加方式</h4>
                <div class="icon-contact" style="text-align: center;">1. 贵站添加本站友链后，在本页面或者给我留言页面留言，附上贵站名称及地址，我会回复评论，如贵站符合要求，添加贵站友链。</div>
            </div>
        <!-- end link -->
        </div>
</div>
{%endblock body%}

blog/templates/message.html
{%extends 'base.html' %}
{% load blog_tags %}
{% block title %}甫式人生丨给我留言{% endblock title %}

{% block description %}
    <meta name="description" content="{% get_title category as bigcategory %}{{ bigcategory.description }}"/>
    {% endblock description %}
    {% block keywords %}
    <meta name="keywords" content="{% get_title category as bigcategory %}{{ bigcategory.keywords }}"/>
    {% endblock keywords %}
{%block body%}
<div class="pagewrapper clearfix">
	
	
		<header class="pageheader clearfix">
			<h1 class="pull-left">
				<a href="https://cuiqingcai.com/message">给我留言</a>
			</h1>
			<div class="pull-right"><!-- 百度分享 -->
	<span class="action action-share bdsharebuttonbox"><i class="fa fa-share-alt"></i>分享 (<span class="bds_count" data-cmd="count" title="累计分享0次">0</span>)<div class="action-popover"><div class="popover top in"><div class="arrow"></div><div class="popover-content"><a href="#" class="sinaweibo fa fa-weibo" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_qzone fa fa-star" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="tencentweibo fa fa-tencent-weibo" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="qq fa fa-qq" data-cmd="sqq" title="分享到QQ好友"></a><a href="#" class="bds_renren fa fa-renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin fa fa-weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_more fa fa-ellipsis-h" data-cmd="more"></a></div></div></div></span>			</div>
		</header>


{% include 'comment_list.html' %}

</div>
{%endblock body%}