blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.contrib.sitemaps.views import sitemap
from apps.fswy.sitemaps import ArticleSitemap, CategorySitemap, TagSitemap

from django.conf import settings
from rest_framework.routers import DefaultRouter
from apps.api import views as api_views
from apps.fswy.feeds import AllArticleRssFeed
if settings.API_FLAG:
    router = DefaultRouter()
    router.register(r'users', api_views.UserListSet)
    router.register(r'articles', api_views.ArticleListSet)
    router.register(r'tags', api_views.TagListSet)
    router.register(r'categorys', api_views.CategoryListSet)

app_name = 'fswy'

# 网站地图
sitemaps = {
    'articles': ArticleSitemap,
    'tags': TagSitemap,
    'categories': CategorySitemap
}


urlpatterns = [
    # 后台管理应用，django自带
    path('admin/', admin.site.urls),
    # 用户
    path('accounts/', include(('apps.user.urls', "apps.user"), namespace="accounts")),
    # fswy 应用
    path('', include(('apps.fswy.urls', "apps.fswy"), namespace="blog")),
    # 评论栏
    path('comment/', include(('apps.comment.urls','apps.comment'), namespace='comment')),
    # 网站地图
    # re_path(r'^sitemap.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path(r'sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # rss订阅
    path(r'feed/', AllArticleRssFeed(), name='rss'),

    path(r'mdeditor/', include(('mdeditor.urls', 'mdeditor'), namespace='mdeditor')),

]
if settings.API_FLAG:
    urlpatterns.append(path(r'api/v1/', include((router.urls, 'router'), namespace='api')))    # restframework

blog/apps/fswy/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from mdeditor.fields import MDTextField   #必须导入

import markdown
import re
# Create your models here.

# 网站导航菜单栏分类表
class BigCategory(models.Model):
    # 导航名称
    name = models.CharField('文章大分类', max_length=20)
    # 用作文章的访问路径，每篇文章有独一无二的标志，下同
    slug = models.SlugField(unique=True)
    # 分类页描述
    description = models.TextField('描述',
                                   max_length=240,
                                   default=settings.SITE_DESCRIPTION,
                                   help_text='用来作为SEO中description,长度参考SEO标准')
    # 分类页Keywords
    keywords = models.TextField('关键字',
                                max_length=240,
                                default=settings.SITE_KEYWORDS,
                                help_text='用来作为SEO中keywords，长度参考SEO标准')
    class Meta:
        verbose_name = '大分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

# 导航栏，分类下的下拉菜单分类
class Category(models.Model):
    # 分类名字
    name = models.CharField('文章分类', max_length=20)
    # slug 用作分类路径，独一无二
    slug = models.SlugField(unique=True)
    # 分类栏目页描述
    description = models.TextField('描述',
                                   max_length=240,
                                   default=settings.SITE_DESCRIPTION,
                                   help_text='用来作为SEO中description,长度参考SEO标准')
    # 对应导航菜单外键
    bigcategory = models.ForeignKey(BigCategory, verbose_name='大分类', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:category',
                       kwargs={'slug': self.slug,
                               'bigslug': self.bigcategory.slug})

    def get_article_list(self):
        return Article.objects.filter(category=self)

# 文章标签
class Tag(models.Model):
    name = models.CharField('文章标签', max_length=20)
    slug = models.SlugField(unique=True)
    description = models.TextField('描述',
                                   max_length=240,
                                   default=settings.SITE_DESCRIPTION,
                                   help_text='用来作为SEO中description,长度参考SEO标准')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag',
                       kwargs={'tag': self.name})

    def get_article_list(self):
        ''' 返回当前标签下所有发表的文章列表 '''
        return Article.objects.filter(tags=self)

# 文章关键词，用来作为SEO中keywords
class Keyword(models.Model):
    name = models.CharField('文章关键词', max_length=20)

    class Meta:
        verbose_name = '关键词'
        verbose_name_plural = verbose_name
        ordering = ['name']

    def __str__(self):
        return self.name

# 文章
class Article(models.Model):
    # 文章默认略缩图
    IMG_LINK = '/static/images/summary.jpg'
    # 文章作者
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name="作者", on_delete=models.CASCADE)
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField('文章摘要',
                               max_length=230,
                               default='文章摘要等同于网页description内容，请务必填写...')
    # 文章内容
    body = MDTextField(verbose_name='文章内容')
    img_link = models.CharField('图片地址', default=IMG_LINK, max_length=255)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    views = models.IntegerField('阅览量', default=0)
    loves = models.IntegerField('喜爱量', default=0)
    # 文章唯一标识符
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Category, verbose_name='文章分类',on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    keywords= models.ManyToManyField(Keyword,
                                     verbose_name='文章关键词',
                                     help_text='文章关键词，用来作为SEO中keywords,最好使用长尾词，3-4个足够')

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        # ??这里负号的作用？？
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]

    def get_absolute_url(self):
        return reverse('blog:article', kwargs={'slug': self.slug})

    # ???
    def body_to_markdown(self):
        return markdown.markdown(self.body, extension=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])

    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def get_pre(self):
        return Article.objects.filter(id_lt=self.id).order_by('-id').first()

    def get_next(self):
        return Article.objects.filter(id_gt=self.id).order_by('id').first()




# 公告
class Activate(models.Model):
    text = models.TextField('公告', null=True)
    is_active = models.BooleanField('是否开启', default=False)
    add_date = models.DateTimeField('提交日期', auto_now_add=True)

    class Meta:
        verbose_name = '公告'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.id

# 幻灯片
class Carousel(models.Model):
    number = models.IntegerField('编号', help_text='编号决定图片播放的顺序，图片不要多于5张')
    title = models.CharField('标题',
                             max_length=20,
                             blank=True,
                             null=True,
                             help_text='标题可以为空')
    content = models.CharField('描述', max_length=80)
    img_url = models.CharField('图片地址', max_length=200)
    url = models.CharField('跳转链接',
                           max_length=200,
                           default='#',
                           help_text='图片跳转的超链接，默认#表示不跳转')

    class Meta:
        verbose_name = '图片轮播'
        verbose_name_plural = verbose_name
        # 编号越小越靠前，添加的时间越晚越靠前
        ordering = ['number', '-id']

    def __str__(self):
        return self.content[:25]

# 友情链接表
class FriendLink(models.Model):
    name = models.CharField('网站名称', max_length=50)
    description = models.CharField('网站描述', max_length=100, blank=True)
    link = models.URLField('友链地址', help_text='请填写http或https开头的完整形式地址')
    logo = models.URLField('网站LOGO', help_text='请填写http或https开头的完整形式地址', blank=True)
    create_date = models.DateTimeField('创建时间', auto_now_add=True)
    is_active = models.BooleanField('是否有效', default=True)
    is_show = models.BooleanField('是否首页展示', default=False)

    class Meta:
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name
        ordering = ['create_date']

    def __str__(self):
        return self.name

    def get_home_url(self):
        '''提取友链的主页'''
        u = re.findall(r'(http|https://.*?)/.*?', self.link)
        home_url = u[0] if u else self.link
        return home_url

    def active_to_false(self):
        self.is_active = False
        self.save(update_fields=['is_active'])

    def show_to_false(self):
        self.is_show =  True
        self.save(update_fields=['is_show'])

blog/templates/oauth/change_profile.html
{% extends 'account/base.html' %}
{% load static %}
{% load oauth_tags %}
{% block title %}
<title>修改资料</title>
{% endblock %}


<!--主要内容块-->
{% block main %}
<main>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card rounded-0 px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">修改资料</h3></div>
                <div class="card-body">
                    <form class="change_profile" method="post" enctype="multipart/form-data"{% get_user_data request.session.uid as user %} action="/accounts/profile/change/">
                        <div id="div_id_link" class="form-group">
                            <label for="id_link" class="form-control-label ">个人网址</label>
                            <div class="">
                                <input type="url" name="link" maxlength="200" class="urlinput form-control" id="id_link" />
                                <small id="hint_id_link" class="text-muted">提示：网址必须填写以http开头的完整形式</small>
                            </div>
                        </div>
                        <div id="div_id_avatar" class="form-group">
                            <label for="id_avatar" class="form-control-label  requiredField">
                                头像<span class="asteriskField">*</span>
                            </label>
                        <div class="">目前: <a href="/media/{{ user.avatar }}">/media/{{ user.avatar }}</a><br />
                修改:
                            <input type="file" name="avatar" class="clearablefileinput" id="id_avatar" />
                        </div>
                        </div>
                        <button class="btn btn-info btn-sm rounded-0" type="submit">更新资料</button>
                    </form>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="login-title"><span>更多操作</span></div>
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/accounts/profile/">查看资料</a>
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/">返回首页</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</main>
{% endblock %}

blog/templates/oauth/profile.html
{%extends 'account/base.html' %}
{% load static %}
{% load oauth_tags %}

{% block title %}
<title>个人中心</title>
{% endblock %}


<!--主要内容块-->
{% block main %}
<main>
<div class="container">
    <div class="row">
        <div class="col-12 col-sm-8 col-md-6 offset-sm-2 offset-md-3 px-xl-5">
            <div class="card rounded-0 px-3 px-lg-4">
                <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item text-center border-0" id="profile-avatar">
{% get_user_data request.session.uid as user %}
                            {% if user %}

                            <img class="avatar" src="/media/{{ user.avatar }}" alt="{{user.username}}">

                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">用户名：</span>
                            <span>{{ user.username }}</span>
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">邮&emsp;箱：</span>
                            <span>{{ user.email }}</span>
                        </li>
                        <li class="list-group-item ml-5 border-0">
                            <span class="font-weight-bold">网&emsp;址：</span>
                            <span>{{ user.link }}</span>
                        </li>
                    </ul>
                </div>
                <div class="text-center mb-5" id="social-login">
                    <div class="more-link mt-3">
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/accounts/profile/change/">修改资料</a>
                        <a class="btn btn-info btn-sm rounded-0 mx-3" href="/">返回首页</a>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</main>
{% endblock main %}